version: '3'

services:
  recipe_app:
    build: .
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - recipe_app
