# Generated by Django 4.2.7 on 2023-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cook_time_recipe_information_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.TextField(),
        ),
    ]
