# Generated by Django 4.2.7 on 2023-12-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_cals_per_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cals_per_serving',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.TextField(null=True),
        ),
    ]
