# Generated by Django 4.2.7 on 2023-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_cals_per_serving_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
