name: Update Image Tag in k8s-apps

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  update-image-tag:
    runs-on: ubuntu-latest
  
    steps:
    - name: Set short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Checkout k8s-apps Repository
      uses: actions/checkout@v2
      with:
        repository: sbeckstrand/k8s-apps
        token: ${{ secrets.K8S_APPS_PAT }}
        path: k8s-apps
    
    - name: Update Image Tag
      run: |
        sed -i "s/tag: \".*\"/tag: \"${{ env.SHORT_SHA }}\"/" k8s-apps/apps/recipe-app/values-image.yaml
    
    - name: Commit and Push Changes
      run: |
        cd k8s-apps
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add apps/recipe-app/values-image.yaml
        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.K8S_APPS_PAT }}
